CREATE TABLE `numbers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(12) NOT NULL,
  `destination` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET `utf8`;

CREATE TABLE `reporters` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(12) NOT NULL,
  `number_id` INT UNSIGNED NOT NULL,
  `token` CHAR(16) NOT NULL,
  `created` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET `utf8`;

CREATE TABLE `messages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sid` VARCHAR(34) NOT NULL,
  `number_id` INT UNSIGNED NOT NULL,
  `reporter_id` INT UNSIGNED NOT NULL,
  `inbound` BOOLEAN NOT NULL,
  `body` TEXT NOT NULL,
  `created` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET `utf8`;

CREATE TABLE `calls` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(12) NOT NULL,
  `number_id` INT UNSIGNED NOT NULL,
  `created` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET `utf8`;
